export const tech = [
  "Flutter",
  "React",
  "React Native",
  "GraphQL",
  "Apollo Client",
  "Redux",
  "Next.js",
  "Node.js",
  "Express",
  "Apollo Server",
  "MongoDB",
  "Firebase",
  "Socket.IO",
  "SSR/SSG",
  "Polygon",
  "IPFS",
  "Docusaurus",
  "Tailwind CSS",
]

export const projects = [
  {
    type: "Team Project",
    title: "Pit Stop",
    description:
      "Pit Stop is a a web3 Formula1 fantasy game platform where players can build their virtual garages by minting F1 cars as NFTs and compete with others by wagering these NFT cars on real life F1 Grand Prix.",
    imgSrc: "/pit-stop.png",
    repoURL: "https://github.com/mizanxali/pit-stop",
    liveURL: "https://pit-stop.vercel.app//",
    submissionURL: "https://devfolio.co/projects/pit-stop-a06f",
    techStack: [
      "Polygon",
      "Solidity",
      "Hardhat",
      "IPFS",
      "MetaMask",
      "Alchemy",
      "Next.js",
      "Tailwind CSS",
    ],
  },
  {
    type: "Personal Project",
    title: "Valcon",
    description:
      "Valcon is a mobile app to find Valorant players to match and play with, by swiping right or left on their gameplay clips. In-game IDs are hidden from players until they match!",
    imgSrc: "/valcon.png",
    repoURL: "https://github.com/mizanxali/valcon",
    techStack: [
      "React Native",
      "Apollo GraphQL Client",
      "Apollo GraphQL Server",
      "TypeGraphQL",
      "Typegoose",
      "MongoDB",
    ],
  },
  {
    type: "Team Project",
    title: "Recon",
    description:
      "Recon is a marketplace for gamers to buy and sell gameplay clips as NFTs. Treating gameplay like the art it is.",
    imgSrc: "/recon.png",
    repoURL: "https://github.com/mizanxali/recon",
    liveURL: "https://recon-pink.vercel.app/",
    submissionURL: "https://devfolio.co/submissions/recon-dcd6",
    techStack: [
      "Polygon",
      "Solidity",
      "Hardhat",
      "IPFS",
      "MetaMask",
      "Alchemy",
      "Next.js",
      "Tailwind CSS",
    ],
  },
  {
    type: "Team Project",
    title: "Raven",
    description:
      "Raven is an Android app that allows you to do more with less. Chat with friends, lend and borrow money from those you trust, find places to visit and share cab rides with friends, all in one app.",
    imgSrc: "/raven.png",
    repoURL: "https://github.com/elecTRON-Fellowship/raven-frontend",
    liveURL:
      "https://drive.google.com/file/d/1EGUI2HfoNEjTll-CEhQP3XuA7qckfkT_/view",
    submissionURL: "https://devpost.com/software/fwallet",
    techStack: ["Flutter", "Firebase"],
  },
  {
    type: "Personal Project",
    title: "UNO Online",
    description:
      "Two player online version of the card game UNO. Real time multiplayer communication supported using web sockets. Includes text chat functionality too.",
    imgSrc: "/uno-online.png",
    repoURL: "https://github.com/mizanxali/uno-online",
    liveURL: "https://uno-online-multiplayer.herokuapp.com/",
    techStack: ["React", "Socket.IO", "Express", "Node.js"],
  },
  {
    type: "Personal Project",
    title: "Drake Lyrics",
    description:
      "Web app to randomly generate lyrics from over 170 different songs by Drake to use as your social media captions/bios. Fetches lyrics from Genius.",
    imgSrc: "/drake-lyrics.png",
    repoURL: "https://github.com/mizanxali/drake-lyrics",
    liveURL: "https://drake-lyrics.herokuapp.com/",
    techStack: ["React", "Express", "Node.js"],
  },
  {
    type: "Personal Project",
    title: "GOTPEDIA",
    description:
      "Online encyclopedia of the world of Game of Thrones. Includes plot for every episode and information about characters and houses. Uses Firebase database.",
    imgSrc: "/gotpedia.png",
    repoURL: "https://github.com/mizanxali/gotpedia",
    liveURL: "https://mizanxali.github.io/gotpedia/",
    techStack: ["React", "React-Bootstrap", "Firebase"],
  },
  {
    type: "Personal Project",
    title: "Cricket Scorer",
    description:
      "Front-end web app to keep score of cricket matches. Includes real time batting and bowling scorecard for each team.",
    imgSrc: "/cricket-scorer.png",
    repoURL: "https://github.com/mizanxali/cricket-scorer-js",
    liveURL: "https://mizanxali.github.io/cricket-scorer-js",
    techStack: ["React", "Redux", "Material-UI"],
  },
  {
    type: "Personal Project",
    title: "mizanxali's Game Zone",
    description:
      "A collection of some browser games made purely with Vanilla JavaScript. Includes 2048, Snake, Pac-Man, Whack-A-Mole, Candy Crush Saga, and more.",
    imgSrc: "/gamezone.png",
    repoURL: "https://github.com/mizanxali/vanilla-js-games",
    liveURL: "https://mizanxali.github.io/vanilla-js-games/",
    techStack: ["HTML", "Javascript"],
  },
  {
    type: "Team Project",
    title: "One Step - elecTRON",
    description:
      "OneStepML is a community-led, open-sourced, e-learning platform for Machine Learning and Data Science.",
    imgSrc: "/onestep-electron.png",
    repoURL: "https://github.com/OneStep-elecTRON/onestep-electron.github.io",
    liveURL: "https://onestep-electron.github.io/",
    techStack: ["React", "Next.js", "Docusaurus", "Typescript"],
  },
  {
    type: "Personal Project",
    title: "GK Quiz App",
    description:
      "A Simple GK Quiz Web App of 10 random general knowledge questions, dynamically fetched from Open Trivia DB. Made with React JS, using Typescript.",
    imgSrc: "/gk-quiz-app.png",
    repoURL: "https://github.com/mizanxali/GK-quiz-app",
    liveURL: "https://mizanxali.github.io/GK-quiz-app",
    techStack: ["React", "Typescript"],
  },
  {
    type: "Personal Project",
    title: "Chat Web App",
    description:
      "Real-time chat web app built with React, Express and Socket.IO. Multiple users can join different rooms using the room name and chat with each other.",
    imgSrc: "/chat-app.png",
    repoURL: "https://github.com/mizanxali/chat-app-react",
    liveURL: "https://chat-app-react-5270.herokuapp.com/",
    techStack: ["React", "Socket.IO", "Express", "Node.js"],
  },
  {
    type: "Course Project",
    title: "Dev Connect",
    description:
      "Full stack social network application for developers. Includes features like user profile, feed, posts, comments.",
    imgSrc: "/dev-connect.png",
    repoURL: "https://github.com/mizanxali/dev-connect",
    liveURL: "https://dev-connect-5270.herokuapp.com/",
    techStack: ["React", "Express", "MongoDB", "Node.js", "JWT"],
  },
  {
    type: "Course Project",
    title: "Netflix Clone",
    description:
      "Front-end Netflix clone with Firebase authentication and Firestore database built as a part of Sonny Sangha's 5 Day React Challenge on YouTube.",
    imgSrc: "/netflix-clone.png",
    repoURL: "https://github.com/mizanxali/netflix-clone",
    liveURL: "https://mizanxali.github.io/netflix-clone/",
    techStack: ["React", "Firebase"],
  },
  {
    type: "Course Project",
    title: "Flamin Burger",
    description:
      "A website to build and order a custom burger. Uses Firebase authentication and database for each user's order history.",
    imgSrc: "/flamin-burger.png",
    repoURL: "https://github.com/mizanxali/flamin-burger",
    liveURL: "https://mizanxali.github.io/flamin-burger/",
    techStack: ["React", "Redux", "Firebase"],
  },
]
